<?php 
require_once('conexion.php');

// traemos los datos de la venta 
    $productoID = $_POST['ID']; // lo hacemos atraves del $_POST['']
    $Producto = $_POST['nombre_producto']; // ....... ----------------------- ...............
    $referencia = $_POST['referencia']; // ....... ----------------------- ...............
    $precio = $_POST['precio']; // ....... ----------------------- ...............
    $peso = $_POST['peso']; // ....... ----------------------- ...............
    $categoria = $_POST['categoria']; // ....... ----------------------- ...............
    $stock = $_POST['stock']; // ....... ----------------------- ...............
    $creado = $_POST['creado']; // ....... ----------------------- ...............
    
    
    if($productoID=="" || $Producto=="" || $referencia=="" || $precio=="" || $categoria==""|| $stock==""){
      echo "*Debe llenar todos los campos.<br/>";
    }else{require_once 'create.php';} 
       
    
    
?>